root: true
env:
    browser: true
    node: true
extends:
    - eslint:recommended
    - plugin:react-hooks/recommended
overrides:
    - files:
          - '*.js'
          - '*.jsx'
      parserOptions:
          ecmaVersion: 2021
      rules:
          strict: error
    - files:
          - '*.ts'
          - '*.tsx'
      parser: '@typescript-eslint/parser'
      parserOptions:
          project:
              - tsconfig.json
              - tsconfig.node.json
      extends:
          - eslint:recommended
          - plugin:react-hooks/recommended
          - plugin:@typescript-eslint/recommended
          - plugin:@typescript-eslint/recommended-requiring-type-checking
      rules:
          '@typescript-eslint/no-non-null-assertion': off
