# https://prettier.io/docs/en/options.html
printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
proseWrap: always
htmlWhitespaceSensitivity: ignore
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
