'use strict'

const MinifyPlugin = require('babel-minify-webpack-plugin')
const CleanWebpackPlugin = require('clean-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin')
const path = require('path')

const config = {
    mode: 'production',
    entry: './demo/index.js',
    output: {
        filename: '[contenthash].js',
        path: path.resolve(__dirname, 'build/demo'),
    },
    module: {
        rules: [
            {
                test: /\.sass$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                        },
                    },
                    'sass-loader',
                ],
            }, {
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader',
            },
        ],
    },
    resolve: {
        alias: {
            'flipping-pages': path.resolve(__dirname, './src/FlippingPages'),
        },
    },
    optimization: {
        minimizer: [
            new OptimizeCSSAssetsPlugin(),
            new MinifyPlugin({}, {comments: false}),
        ]
    },
    plugins: [
        new CleanWebpackPlugin(['build/demo'], {exclude: ['.git']}),
        new MiniCssExtractPlugin({
            filename: '[contenthash].css',
        }),
        new HtmlWebpackPlugin({
            template: 'demo/index.html',
            minify: {
                collapseBooleanAttributes: true,
                collapseInlineTagWhitespace: true,
                collapseWhitespace: true,
                includeAutoGeneratedTags: false,
                removeAttributeQuotes: true,
                removeEmptyAttributes: true,
                removeRedundantAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                sortAttributes: true,
                sortClassName: true,
            },
        }),
    ],
}

module.exports = config